export const CHECKER_AUTH_SERVICE = 'CHECKER_AUTH_SERVICE'
export const CHECKER_SCAN_QUEUE_SERVICE = 'CHECKER_SCAN_QUEUE_SERVICE'
export const CHECKER_ORDER_SERVICE = 'CHECKER_ORDER_SERVICE'
export const CHECKER_ORDER_QUEUE_SERVICE = 'CHECKER_ORDER_QUEUE_SERVICE'
